# frozen_string_literal: true

source 'https://rubygems.org'
ruby '4.0.4'

gem 'mcp', '~> 0.16.0'
gem 'json', '~> 2.19.5'
gem 'erb', '>= 4.0.4.1'
gem 'net-imap', '~> 0.6.4'

group :development, :test do
  gem 'minitest'
  gem 'rake'
end
